### PR TITLE
Issue#37: Added the Pomodro Widget

### PR DESCRIPTION
**Pull request by ayyush08**
Hi,

The pomodro widget issue I raised is done.

I have successfully added the widget to the collection without any interference to the rest widgets.

Kindly merge my PR.

### CODE REVIEW

**Comment by mohitahlawat2001** [comment]
add photo pls

**Review by mohitahlawat2001 — CHANGES_REQUESTED** [review]
its look like similar to normal timer , make it look like pomodro clock

**Comment by ayyush08** [comment]
@mohitahlawat2001 Can you please elaborate?
The timer works exactly like Pomodro Timer.
After 25minutes are over, user gets an alert for 5minutes break, and the 5 minutes break timer starts and vice-versa.
By looks do you mean the styling??

**Comment by mohitahlawat2001** [comment]
yes talking about style

**Comment by ayyush08** [comment]
Screenshot 2024-10-08 211526
Something like this??

**Comment by mohitahlawat2001** [comment]
something like this 
image

**Comment by ayyush08** [comment]
Screenshot 2024-10-09 184850
Check to see , if this is fine and can be merged@mohitahlawat2001

**Review by mohitahlawat2001 — CHANGES_REQUESTED** [review]
can you reduce size of this compoenet , also make button design like normal button, you can also remove some widgets from main page , as too many widgets shown right now,

**Comment by ayyush08** [comment]
Screenshot 2024-10-10 073417
How about now??

**Review by mohitahlawat2001 — APPROVED** [review]

**Pull request merged**
