### PR TITLE
Added BookWidget component

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds a new component called BookWidget. The BookWidget component allows users to search for books by title using the Google Books API. It displays the search results, including the book title, authors, published date, and ISBN-13. Users can also copy the ISBN-13 to the clipboard.

### CODE REVIEW

**Comment by mohitahlawat2001** [comment]
can you post photo or video regarding this ,

**Comment by ghost** [comment]
Sure, here is a video:

https://github.com/user-attachments/assets/fe0f4b3e-adc6-45dc-90ad-54c592953ee7

**Comment by mohitahlawat2001** [comment]
could you decrease height little bit , it too big right now,

**Comment by ghost** [comment]
How much?

**Comment by mohitahlawat2001** [comment]
2-3 book detail can be displayed at a time

**Comment by ghost** [comment]
HI @mohitahlawat2001, I would like to notify you that I fixed a CSS issue that apparently occurred when the video widget component was merged.
Take a look at the screenshot:
iScreen Shoter - Google Chrome - 241007145115
Do you see the blue color in the tic-tac-toe game? That was due to CSS specificity in the CSS file of the video widget. I fixed it. Please take a look at the changes.
Now could you please merge my PR?
I would do a second PR for my improved book widget.

**Comment by ghost** [comment]
This is how I think it should suppose to be:
iScreen Shoter - Google Chrome - 241007150028

**Review by mohitahlawat2001 — APPROVED** [review]

**Comment by mohitahlawat2001** [comment]
thank you for you work

**Pull request merged**
