### PR TITLE
Completely responsive for all devices

### PR DESCRIPTION
**Pull request by ParvamShah1**
The website is now fully responsive across all devices, ensuring a seamless and user-friendly experience on desktops, tablets, and mobile phones.
These optimizations ensure the website maintains a polished, consistent layout, delivering a smooth experience whether viewed on large desktop monitors or small mobile devices.
image
image

It was nice working on your website . Please merge my pr.

Thanks !

### CODE REVIEW

**Review by mohitahlawat2001 — CHANGES_REQUESTED** [review]
make upper button as it is before , now it is not looking good

**Comment by ParvamShah1** [comment]
Buttons changed to how they were before .
Please merge the new commit.
image
Thanks!

**Review by mohitahlawat2001 — CHANGES_REQUESTED** [review]
image
image

there is change after your commit , they should look like i provided photo

**Comment by ParvamShah1** [comment]
can you state what are the exact changes that i need to rectify ?

**Comment by mohitahlawat2001** [comment]
some which css which is common and you may be overwrite this

**Comment by ParvamShah1** [comment]
Please check now if everything is good.
image
Please tell if any changes are required.
Otherwise please merge my pr.
Thanks!

**Comment by ParvamShah1** [comment]
Hi,

I hope you're doing well! I just wanted to kindly follow up on my pull request #41 . If there are any changes or improvements you'd like me to make, please do let me know. I'd be happy to address them.

Thank you for your time and consideration, and I look forward to your feedback!

Best regards,

**Comment by mohitahlawat2001** [comment]
i not able to see any change

**Pull request merged**
